image: localhost:5000/sample-ci-python:3.8

before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip show myapp

run tests:
  only:
    - master
  tags:
    - python3
    - tests
  script:
        - cd /workspace
        - python -m pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'
